-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 15:24:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema m5prog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `aanbiedingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aanbiedingen` (
  `idaanbiedingen` INT NOT NULL,
  `soort_aanbieding` VARCHAR(45) NULL,
  PRIMARY KEY (`idaanbiedingen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `type_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `type_product` (
  `idtype_product` INT NOT NULL AUTO_INCREMENT,
  `type_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producten` (
  `idProducten` INT NOT NULL,
  `product_naam` VARCHAR(45) NOT NULL,
  `product_prijs` DECIMAL NOT NULL,
  `aanbiedingen_idaanbiedingen` INT NULL,
  `type_product_idtype_product` INT NOT NULL,
  PRIMARY KEY (`idProducten`),
  INDEX `fk_Producten_aanbiedingen_idx` (`aanbiedingen_idaanbiedingen` ASC) VISIBLE,
  INDEX `fk_Producten_type_product1_idx` (`type_product_idtype_product` ASC) VISIBLE,
  CONSTRAINT `fk_Producten_aanbiedingen`
    FOREIGN KEY (`aanbiedingen_idaanbiedingen`)
    REFERENCES `aanbiedingen` (`idaanbiedingen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producten_type_product1`
    FOREIGN KEY (`type_product_idtype_product`)
    REFERENCES `type_product` (`idtype_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gebruiker` (
  `idgebruiker` INT NOT NULL,
  `gebruiker_naam` VARCHAR(45) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idgebruiker`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
